name: Distribution update

on:
  push:
    tags:
  workflow_dispatch: ~

env:
  GH_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-api-platform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Update distribution
        run: gh workflow run -R api-platform/api-platform release.yml -f tag=${{ github.ref_name }}


